#!/usr/bin/env bash
# Script that reads /etc/passwd and displays username, UID and home directory

while IFS=':' read -r username _ uid _ _ _ home; do
    echo "$username $uid $home"
done < /etc/passwd
