#!/usr/bin/env bash
# This script tells a story based on the /etc/passwd file

# Set IFS to colon (:) to split each field in /etc/passwd
IFS=":"

# Read the /etc/passwd file line by line
while read -r username password uid gid fullname home shell
do
    # Display the user information in the required format
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $fullname"
done < /etc/passwd
