#!/usr/bin/env bash
# Count occurrences of "IP HTTP_CODE" pairs from Apache logs

awk '{print $1, $9}' apache-access.log \
    | awk '{count[$0]++} END {for (c in count) print count[c], c}' \
    | sort -nr
