#!/usr/bin/env bash
#pid
PID_FILE="/var/run/myscript.pid"
cleanup() {
  rm -f "$PID_FILE"
  exit 0
}
trap 'echo "I hate the kill command"; cleanup' SIGTERM
echo $$ > "$PID_FILE"
while true
do
  sleep 2
done
